In [ ]:
# pip install opencv-python-headless
# pip install pillow
# pip install pytesseract

In [2]:
import json
import pandas as pd

data = json.load(
    open(
        "/home/rsoko/private/001-wedding-venue/data/processed/adobe_extracted/ Monserate Winery (11)-merged/structuredData.json"
    )
)
page = ""
for ele in data["elements"]:
    if "Page" in ele.keys():
        page = ele["Page"]

    elif ("Text" in ele.keys()) and ("Figure" not in ele["Path"]):
        df = pd.DataFrame({"text": ele["Text"]}, index=[0])

{'version': {'json_export': '210',
  'page_segmentation': '55',
  'schema': '1.1.0',
  'structure': '1.1125.0',
  'table_structure': '5'},
 'extended_metadata': {'ID_instance': '4D 04 66 82 51 BB B2 11 0A 00 1E 69 5C 61 78 4F ',
  'ID_permanent': '33 A5 0E 6D CF 57 63 F8 8B 97 3B 18 A0 63 7F 73 ',
  'has_acroform': False,
  'has_embedded_files': False,
  'is_XFA': False,
  'is_certified': False,
  'is_encrypted': False,
  'is_digitally_signed': False,
  'language': 'en',
  'page_count': 31,
  'pdf_version': '1.6',
  'pdfa_compliance_level': '',
  'pdfua_compliance_level': ''},
 'elements': [{'Bounds': [-0.7674102783203125,
    474.1995391845703,
    612.7766265869141,
    1087.7435913085938],
   'ObjectID': 2015,
   'Page': 0,
   'Path': '//Document/Figure',
   'attributes': {'BBox': [0.0,
     474.97299999999814,
     611.9749999999767,
     799.9199999999837],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart0.png']},
  {'Bounds': [-0.7674102783203125,
    474.1995391845703,
    612.7766265869141,
    1087.7435913085938],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'ObjectID': 2015,
   'Page': 0,
   'Path': '//Document/Figure',
   'Text': 'Weddings ',
   'TextSize': 50.50700378417969,
   'attributes': {'BBox': [0.0,
     474.97299999999814,
     611.9749999999767,
     799.9199999999837],
    'Placement': 'Block'}},
  {'Bounds': [46.10369873046875,
    749.8638763427734,
    201.0263214111328,
    796.0766906738281],
   'ClipBounds': [46.10369873046875,
    749.8638763427734,
    201.0263214111328,
    796.0766906738281],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 2005,
   'Page': 1,
   'Path': '//Document/H1',
   'Text': 'Congratulations ',
   'TextSize': 34.282501220703125,
   'attributes': {'LineHeight': 41.125}},
  {'Bounds': [11.449295043945312,
    317.37403869628906,
    230.48680114746094,
    824.3345947265625],
   'ClipBounds': [11.449295043945312,
    317.37403869628906,
    230.48680114746094,
    824.3345947265625],
   'ObjectID': 2006,
   'Page': 1,
   'Path': '//Document/Figure[2]',
   'attributes': {'BBox': [11.399499999999989,
     317.29999999998836,
     227.0309999999954,
     799.9199999999837],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart1.png']},
  {'Bounds': [11.449295043945312,
    317.37403869628906,
    230.48680114746094,
    824.3345947265625],
   'ClipBounds': [11.449295043945312,
    317.37403869628906,
    230.48680114746094,
    824.3345947265625],
   'Font': {'alt_family_name': 'Myriad Pro',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Myriad Pro',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AIARXI+MyriadPro-Light',
    'subset': True,
    'weight': 300},
   'HasClip': True,
   'ObjectID': 2006,
   'Page': 1,
   'Path': '//Document/Figure[2]',
   'Text': 'Congratulations on your engagement, and welcome to a world of enchanting beauty and timeless romance. Experience the captivating allure of Monserate Winery as you explore our three exquisite venues nestled within sprawling vineyards, each graced by a serene lake and breathtaking scenery. Located in the charming hills of Fallbrook, CA, our winery offers a captivating destination, bathed in the warm glow of the Southern California sun. Embrace the love and tranquility that permeate every corner of Monserate Winery, where elegance meets serenity, and dreams are woven into reality. Let us be your perfect haven for a wedding experience that will forever live in your hearts. Cheers to your love story, and welcome to Monserate Winery! ',
   'TextSize': 13.5,
   'attributes': {'BBox': [11.399499999999989,
     317.29999999998836,
     227.0309999999954,
     799.9199999999837],
    'Placement': 'Block'}},
  {'Bounds': [35.39599609375,
    275.49127197265625,
    208.41978454589844,
    321.70408630371094],
   'ClipBounds': [35.39599609375,
    275.49127197265625,
    208.41978454589844,
    321.70408630371094],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 2007,
   'Page': 1,
   'Path': '//Document/H1[2]',
   'Text': 'Our Commitment ',
   'TextSize': 34.282501220703125,
   'attributes': {'LineHeight': 41.125,
    'SpaceAfter': 5.75,
    'TextAlign': 'Center'}},
  {'Bounds': [11.423904418945312,
    18.496200561523438,
    227.180908203125,
    277.4936981201172],
   'ClipBounds': [11.423904418945312,
    18.496200561523438,
    227.180908203125,
    277.4936981201172],
   'Font': {'alt_family_name': 'Myriad Pro',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Myriad Pro',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AIARXI+MyriadPro-Light',
    'subset': True,
    'weight': 300},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 2008,
   'Page': 1,
   'Path': '//Document/P',
   'Text': 'Your wedding day marks a momentous occasion, one of the most important days of your life. At Monserate Winery, we hold a fervent belief that your wedding should authentically reflect the unique story and love that has brought you to this special moment. From the very instant you set foot on our property to the heartwarming moment you walk down the aisle, our unwavering commitment is to craft an unforgettable experience that you will cherish for a lifetime. ',
   'TextSize': 13.5,
   'attributes': {'LineHeight': 20.25, 'TextAlign': 'Center'}},
  {'Bounds': [237.21176147460938,
    7.9799957275390625,
    612.1967315673828,
    800.0299377441406],
   'ClipBounds': [237.21176147460938,
    7.9799957275390625,
    612.1967315673828,
    800.0299377441406],
   'ObjectID': 2009,
   'Page': 1,
   'Path': '//Document/Figure[3]',
   'attributes': {'BBox': [237.5899999999965,
     8.072199999999611,
     611.9749999999767,
     799.9199999999837],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart2.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1989,
   'Page': 2,
   'Path': '//Document/Figure[4]',
   'attributes': {'BBox': [9.959589999999935,
     436.0939999999973,
     264.94899999999325,
     781.679999999993],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart3.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1989,
   'Page': 2,
   'Path': '//Document/Figure[4]',
   'attributes': {'BBox': [9.959589999999935,
     436.0939999999973,
     264.94899999999325,
     781.679999999993],
    'Placement': 'Block'}},
  {'Bounds': [11.039993286132812,
    244.67999267578125,
    65.75999450683594,
    512.5200042724609],
   'ObjectID': 1990,
   'Page': 2,
   'Path': '//Document/Figure[5]',
   'attributes': {'BBox': [11.03959999999961,
     244.82199999999284,
     65.75729999999749,
     512.4109999999928],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart4.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1991,
   'Page': 2,
   'Path': '//Document/Figure[6]',
   'attributes': {'BBox': [8.759639999999763,
     245.06199999999808,
     267.58899999999267,
     427.9349999999977],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart5.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1991,
   'Page': 2,
   'Path': '//Document/Figure[6]',
   'attributes': {'BBox': [8.759639999999763,
     245.06199999999808,
     267.58899999999267,
     427.9349999999977],
    'Placement': 'Block'}},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1992,
   'Page': 2,
   'Path': '//Document/Figure[7]',
   'attributes': {'BBox': [288.22799999998824,
     547.8099999999977,
     601.295999999973,
     782.039999999979],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart6.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1992,
   'Page': 2,
   'Path': '//Document/Figure[7]',
   'attributes': {'BBox': [288.22799999998824,
     547.8099999999977,
     601.295999999973,
     782.039999999979],
    'Placement': 'Block'}},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1993,
   'Page': 2,
   'Path': '//Document/Figure[8]',
   'attributes': {'BBox': [280.54899999999907,
     248.18199999999342,
     434.2619999999879,
     536.7699999999895],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart7.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1993,
   'Page': 2,
   'Path': '//Document/Figure[8]',
   'attributes': {'BBox': [280.54899999999907,
     248.18199999999342,
     434.2619999999879,
     536.7699999999895],
    'Placement': 'Block'}},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1994,
   'Page': 2,
   'Path': '//Document/Figure[9]',
   'attributes': {'BBox': [443.2619999999879,
     247.46199999999953,
     598.6559999999881,
     535.6899999999732],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart8.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1994,
   'Page': 2,
   'Path': '//Document/Figure[9]',
   'attributes': {'BBox': [443.2619999999879,
     247.46199999999953,
     598.6559999999881,
     535.6899999999732],
    'Placement': 'Block'}},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1995,
   'Page': 2,
   'Path': '//Document/Figure[10]',
   'attributes': {'BBox': [9.959589999999935,
     8.431879999999637,
     266.3889999999956,
     236.54299999999785],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart9.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1995,
   'Page': 2,
   'Path': '//Document/Figure[10]',
   'attributes': {'BBox': [9.959589999999935,
     8.431879999999637,
     266.3889999999956,
     236.54299999999785],
    'Placement': 'Block'}},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1996,
   'Page': 2,
   'Path': '//Document/Figure[11]',
   'attributes': {'BBox': [277.1889999999985,
     8.551879999999983,
     600.0959999999905,
     237.6229999999996],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart10.png']},
  {'Bounds': [-0.1875, -0.1875152587890625, 612.1875, 803.9660034179688],
   'ObjectID': 1996,
   'Page': 2,
   'Path': '//Document/Figure[11]',
   'attributes': {'BBox': [277.1889999999985,
     8.551879999999983,
     600.0959999999905,
     237.6229999999996],
    'Placement': 'Block'}},
  {'Bounds': [8.928497314453125,
    694.8950653076172,
    278.6188659667969,
    789.4199371337891],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1973,
   'Page': 3,
   'Path': '//Document/P[2]',
   'Text': 'The Big Day ',
   'TextSize': 70.12229919433594,
   'attributes': {'LineHeight': 84.125, 'SpaceAfter': 18}},
  {'Bounds': [22.669692993164062,
    616.7053375244141,
    81.17288208007812,
    662.9317626953125],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1974,
   'Page': 3,
   'Path': '//Document/H1[3]',
   'Text': 'Style ',
   'TextSize': 34.2926025390625,
   'attributes': {'LineHeight': 41.125, 'SpaceAfter': 10.25}},
  {'Bounds': [22.654006958007812,
    478.6322784423828,
    239.53367614746094,
    616.6683044433594],
   'Font': {'alt_family_name': 'Myriad Pro',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Myriad Pro',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AIARXI+MyriadPro-Light',
    'subset': True,
    'weight': 300},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1975,
   'Page': 3,
   'Path': '//Document/P[3]',
   'Text': 'Make the most of our three stunning venues and customize your special day to your liking. Choose where and how you would like to set up your ceremony, cocktail, and reception at each venue. ',
   'TextSize': 15.698394775390625,
   'attributes': {'LineHeight': 19.875, 'SpaceAfter': 6.5}},
  {'Bounds': [25.947601318359375,
    419.5031280517578,
    78.65531921386719,
    465.72955322265625],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1976,
   'Page': 3,
   'Path': '//Document/H1[4]',
   'Text': 'Stay ',
   'TextSize': 34.2926025390625,
   'attributes': {'LineHeight': 41.125, 'SpaceAfter': 17.875}},
  {'Bounds': [22.6383056640625,
    253.80320739746094,
    250.5476837158203,
    411.74481201171875],
   'Font': {'alt_family_name': 'Myriad Pro',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Myriad Pro',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AIARXI+MyriadPro-Light',
    'subset': True,
    'weight': 300},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1977,
   'Page': 3,
   'Path': '//Document/P[4]',
   'Text': "Conveniently located off the 15 and 76 freeways, your guests will have their choice between a plethora of Airbnb's, Vrbo's, hotels, Casino's all within 10 miles. From elevated to economical, there will be no shortage of options for your wedding guests' stay. ",
   'TextSize': 15.698394775390625,
   'attributes': {'LineHeight': 19.875, 'SpaceAfter': 6.75}},
  {'Bounds': [25.947601318359375,
    194.3567352294922,
    90.48626708984375,
    240.58316040039062],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1978,
   'Page': 3,
   'Path': '//Document/H1[5]',
   'Text': 'Sights ',
   'TextSize': 34.2926025390625,
   'attributes': {'LineHeight': 41.125, 'SpaceAfter': 17.75}},
  {'Bounds': [25.947601318359375,
    28.788803100585938,
    251.47080993652344,
    186.73040771484375],
   'Font': {'alt_family_name': 'Myriad Pro',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Myriad Pro',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AIARXI+MyriadPro-Light',
    'subset': True,
    'weight': 300},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1979,
   'Page': 3,
   'Path': '//Document/P[5]',
   'Text': "Situated between downtown San Diego and Orange County, we're the perfect destination for your visiting wedding guests. Your guests will have a variety of airports to fly into and plenty of exciting sights to see around Southern California. ",
   'TextSize': 15.698394775390625,
   'attributes': {'LineHeight': 19.875, 'SpaceAfter': 11.25}},
  {'Bounds': [282.0850830078125,
    7.6337127685546875,
    612.2712249755859,
    799.9203491210938],
   'ObjectID': 1980,
   'Page': 3,
   'Path': '//Document/Figure[12]',
   'attributes': {'BBox': [282.3489999999874,
     7.952209999999923,
     611.9749999999767,
     799.9199999999837],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart11.png']},
  {'Bounds': [-0.0650634765625,
    7.9199981689453125,
    277.81288146972656,
    799.9199981689453],
   'ObjectID': 1917,
   'Page': 4,
   'Path': '//Document/Figure[13]',
   'attributes': {'BBox': [0.0,
     7.952209999999923,
     277.4289999999892,
     799.9199999999837],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart12.png']},
  {'Bounds': [331.58750915527344,
    716.4183807373047,
    566.093017578125,
    809.4202728271484],
   'ObjectID': 1918,
   'Page': 4,
   'Path': '//Document/Figure[14]',
   'attributes': {'BBox': [331.5469999999914,
     747.4819999999891,
     548.8579999999783,
     799.9199999999837],
    'Placement': 'Block'},
   'filePaths': ['figures/fileoutpart13.png']},
  {'Bounds': [331.58750915527344,
    716.4183807373047,
    566.093017578125,
    809.4202728271484],
   'Font': {'alt_family_name': 'Italianno',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Italianno',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AKTIHC+Italianno-Regular',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'ObjectID': 1918,
   'Page': 4,
   'Path': '//Document/Figure[14]',
   'Text': 'The Details ',
   'TextSize': 68.99250793457031,
   'attributes': {'BBox': [331.5469999999914,
     747.4819999999891,
     548.8579999999783,
     799.9199999999837],
    'Placement': 'Block'}},
  {'Bounds': [382.1763000488281,
    694.0701141357422,
    516.2698974609375,
    717.1461944580078],
   'Font': {'alt_family_name': 'Assassin',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Assassin',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AWWRXQ+Assassin',
    'subset': True,
    'weight': 400},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1919,
   'Page': 4,
   'Path': '//Document/H1[6]',
   'Text': 'THE VENUE ',
   'TextSize': 20.677505493164062,
   'attributes': {'LineHeight': 24.75, 'TextAlign': 'Center'}},
  {'Bounds': [312.18260192871094,
    659.6100921630859,
    578.0663146972656,
    694.4181518554688],
   'Font': {'alt_family_name': 'Myriad Pro',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Myriad Pro',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AIARXI+MyriadPro-Light',
    'subset': True,
    'weight': 300},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1920,
   'Page': 4,
   'Path': '//Document/P[6]',
   'Text': 'Complimentary use for an one hour ceremony rehearsal ',
   'TextSize': 14.19000244140625,
   'attributes': {'LineHeight': 18, 'TextAlign': 'Center'}},
  {'Bounds': [307.69439697265625,
    623.6100921630859,
    582.5745697021484,
    658.4181518554688],
   'Font': {'alt_family_name': 'Myriad Pro',
    'embedded': True,
    'encoding': 'Identity-H',
    'family_name': 'Myriad Pro',
    'font_type': 'CIDFontType2',
    'italic': False,
    'monospaced': False,
    'name': 'AIARXI+MyriadPro-Light',
    'subset': True,
    'weight': 300},
   'HasClip': True,
   'Lang': 'en',
   'ObjectID': 1921,
   'Page': 4,
   'Path': '//Document/P[7]',

In [1]:
from tqdm import tqdm
import cv2
import numpy as np
from PIL import Image
import pytesseract
from pathlib import Path

import pandas as pd


def photo_properties(image_path) -> dict:
    # Read image using PIL first (for OCR)
    pil_image = Image.open(image_path)

    # Get OCR data including bounding boxes
    ocr_data = pytesseract.image_to_data(
        pil_image, output_type=pytesseract.Output.DATAFRAME
    )

    # Calculate total area of text bounding boxes
    total_text_area = 0
    try:
        if not ocr_data.empty:
            # Filter out empty text entries and calculate areas
            valid_boxes = ocr_data[
                ocr_data["text"].notna() & (ocr_data["text"].str.strip() != "")
            ]
            total_text_area = sum(
                row["width"] * row["height"] for _, row in valid_boxes.iterrows()
            )
    except Exception as e:
        pass
    # Get image dimensions for total area
    width, height = pil_image.size
    total_image_area = width * height

    # Calculate text density as ratio of text area to image area
    text_density = total_text_area / total_image_area if total_image_area > 0 else 0

    # Convert to OpenCV format for edge detection
    cv_image = cv2.imread(str(image_path))
    gray = cv2.cvtColor(cv_image, cv2.COLOR_BGR2GRAY)

    # Image properties
    height, width = gray.shape
    total_pixels = height * width

    # Edge detection
    edges = cv2.Canny(gray, 100, 200)
    edge_pixels = np.count_nonzero(edges)
    edge_density = edge_pixels / total_pixels

    # Analyze color variation
    color_std = np.std(cv_image, axis=(0, 1)).mean()

    return {
        "width": width,
        "height": height,
        "total_pixels": total_pixels,
        "text_density": text_density,
        "color_std": color_std,
        "edge_density": edge_density,
    }


def predict_image_quality(properties: dict) -> bool:
    X = pd.DataFrame(
        {
            "width": properties["width"],
            "height": properties["height"],
            "total_pixels": properties["total_pixels"],
            "text_density": properties["text_density"],
            "color_std": properties["color_std"],
            "edge_density": properties["edge_density"],
        },
        index=[0],
    )
    return bool(model.predict(X)[0])


def is_photo(image_path, text_threshold=0.05, color_std_threshold=30):
    """
    Determines if an image is likely a photo rather than text/logo/menu.

    Args:
        image_path: Path to the image file
        text_threshold: Maximum ratio of text area to consider as photo
        edge_threshold: Threshold for edge density to distinguish photos from graphics

    Returns:
        bool: True if the image is likely a photo, False otherwise
    """
    properties = photo_properties(image_path)
    # Classification rules
    is_likely_photo = (
        properties["text_density"] < text_threshold  # Not too much text
        and properties["color_std"]
        > color_std_threshold  # Has reasonable color variation
    )

    return is_likely_photo


def filter_photos(input_directory):
    """
    Processes a directory of images and copies only the photos to the output directory.

    Args:
        input_directory: Path to directory containing input images
        output_directory: Path to directory where photos should be copied
    """
    input_path = Path(input_directory)
    output_path = input_path.with_name(input_path.stem + "_accepted")
    output_path.mkdir(parents=True, exist_ok=True)
    rejected_path = input_path.with_name(input_path.stem + "_rejected")
    rejected_path.mkdir(parents=True, exist_ok=True)

    image_extensions = {".jpg", ".jpeg", ".png", ".bmp", ".tiff"}
    if not Path(input_directory).exists():
        return
    for image_file in tqdm(list(input_path.iterdir())):
        if image_file.suffix.lower() in image_extensions:
            try:
                if is_photo(image_file):
                    Image.open(image_file).save(output_path / image_file.name)
                else:
                    Image.open(image_file).save(rejected_path / image_file.name)
            except Exception as e:
                pass


# Example usage
if __name__ == "__main__":
    filter_photos(
        "../data/processed/adobe_extracted/ Monserate Winery (11)-merged/figures",
    )

100%|██████████| 2/2 [00:00<00:00, 9608.94it/s]

In [2]:
import pandas as pd
from pathlib import Path

img_dir = Path("../data/processed/train")
bad_img_dir = Path("../data/processed/rejected_pdf_images")
df = pd.DataFrame()
for img in tqdm(list(img_dir.iterdir())):
    if img.name in list(bad_img_dir.iterdir()):
        good_img = False
    else:
        good_img = True
    try:
        properties = photo_properties(img)
    except Exception as e:
        continue
    properties.update({"img": img.name, "good_img": good_img})
    df = pd.concat([df, pd.DataFrame(properties, index=[len(df)])], ignore_index=True)
img = pd.Series(list(x.name for x in img_dir.iterdir()))
good_img = ~img.isin(list(x.name for x in bad_img_dir.iterdir()))
df["good_img"] = good_img
df["img"] = img
df.good_img.value_counts()

df

100%|██████████| 473/473 [13:01<00:00,  1.65s/it]

,width,height,total_pixels,text_density,color_std,edge_density,img,good_img
0,13,13,169,0.000000,0.000000,0.000000,2024 Queen Mary Ceremony Locations-merged_file...,False
1,1525,441,672525,0.000000,67.095970,0.117889,2023 Continental Catering Full Service Menu_fi...,True
2,2550,1176,2998800,0.000000,53.423644,0.037985,2025 Alta Vista Wedding Packages_fileoutpart14...,True
3,1032,1117,1152744,0.000000,56.640216,0.047789,Monserate Winery (11)-merged_fileoutpart58.png,True
4,725,1449,1050525,0.000000,66.490859,0.065672,Monserate Winery (11)-merged_fileoutpart28.png,True
...,...,...,...,...,...,...,...,...
468,1051,1670,1755170,0.000000,60.955133,0.090637,2024 Queen Mary Ceremony Locations-merged_file...,True
469,2550,2746,7002300,0.029906,32.266259,0.005549,_2024 Weddings at Lake Arrowhead~-merged_fileo...,False
470,2568,3299,8471832,0.000000,79.503724,0.015911,2023 Estancia La Jolla Wedding Brochure-merged...,True
471,2402,1893,4546986,0.000000,58.661994,0.094875,2024 L_Auberge del mar_fileoutpart2.png,True
472,18,17,306,0.000000,82.266245,0.189542,2025_Seventh_Place_Event_Packet-merged_fileout...,False

In [5]:
import itables

itables.show(df)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import numpy as np

# Prepare features and target
features = [
    "width",
    "height",
    "total_pixels",
    "text_density",
    "color_std",
    "edge_density",
]
X = df[features]
y = df["good_img"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train a random forest model
model = RandomForestClassifier(
    n_estimators=100,  # number of trees
    max_depth=None,  # maximum depth of trees
    min_samples_split=2,
    random_state=42,
)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print feature importance
feature_importance = pd.DataFrame(
    {"feature": features, "importance": model.feature_importances_}
)
print("\nFeature Importance:")
print(feature_importance.sort_values("importance", ascending=False))


# Function to predict if a new image is good
def predict_image_quality(properties: dict) -> bool:
    X = pd.DataFrame(
        {
            "width": properties["width"],
            "height": properties["height"],
            "total_pixels": properties["total_pixels"],
            "text_density": properties["text_density"],
            "color_std": properties["color_std"],
            "edge_density": properties["edge_density"],
        },
        index=[0],
    )
    return bool(model.predict(X)[0])

Classification Report:
              precision    recall  f1-score   support

       False       1.00      0.93      0.96        41
        True       0.95      1.00      0.97        54

    accuracy                           0.97        95
   macro avg       0.97      0.96      0.97        95
weighted avg       0.97      0.97      0.97        95


Feature Importance:
        feature  importance
1        height    0.295951
2  total_pixels    0.194837
4     color_std    0.158502
0         width    0.145348
3  text_density    0.112306
5  edge_density    0.093056

In [8]:
import pickle

with open("model.bin", "wb") as f:
    pickle.dump(model, f)

In [ ]:
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier

MODEL_PATH=Path("model.bin")

def load_is_photo_classifier()->RandomForestClassifier:
    with open(MODEL_PATH, "rb") as f:
        model = pickle.load(f)
    return model

def is_photo(image_path: Path | str):

In [9]:
with open("model.bin", "rb") as f:  # 'rb' for binary read mode
    model = pickle.load(f)

In [10]:
y_pred = model.predict(X_test)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print feature importance
feature_importance = pd.DataFrame(
    {"feature": features, "importance": model.feature_importances_}
)
print("\nFeature Importance:")
print(feature_importance.sort_values("importance", ascending=False))

Classification Report:
              precision    recall  f1-score   support

       False       1.00      0.93      0.96        41
        True       0.95      1.00      0.97        54

    accuracy                           0.97        95
   macro avg       0.97      0.96      0.97        95
weighted avg       0.97      0.97      0.97        95


Feature Importance:
        feature  importance
1        height    0.295951
2  total_pixels    0.194837
4     color_std    0.158502
0         width    0.145348
3  text_density    0.112306
5  edge_density    0.093056

In [46]:
import shutil

figures_dir = Path("../data/processed/adobe_extracted")
good_img_dir = Path("../data/processed/good_figures")
good_img_dir.mkdir(exist_ok=True)

for img in tqdm(list(Path("../data/processed/tmp_figures").iterdir())):
    if not img.is_file():
        continue

    venue, part = img.name.split("_fileout")
    out_dir = Path(f"../data/processed/good_figures/{venue}")
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / f"fileout{part}"
    img_properties = photo_properties(img)
    if predict_image_quality(img_properties):
        shutil.copy2(img, out_path)
    else:
        pass

  0%|          | 0/7757 [00:00<?, ?it/s]

100%|██████████| 7757/7757 [1:23:19<00:00,  1.55it/s]

In [ ]:
for img in Path("../data/processed/train").iterdir():
    venue, _, part = img.name.split("_fileout")
    out_path = Path(f"../data/processed/good_figures/{venue}/fileout{part}")

In [32]:
list((venue / "figures").iterdir())

[]

In [3]:
df["good_img"].value_counts()

good_img
True    473
Name: count, dtype: int64

In [23]:
from pathlib import Path
from tqdm import tqdm

# Create output directory
output_dir = Path("../data/processed/tmp_figures")
output_dir.mkdir(exist_ok=True)

# Iterate through company directories
adobe_dir = Path("../data/processed/adobe_extracted")
for company_dir in tqdm(list(adobe_dir.iterdir())):
    if not company_dir.is_dir() or company_dir.name.startswith(
        "."
    ):  # Skip .DS_Store etc
        continue

    figures_dir = company_dir / "figures"
    if not figures_dir.exists():
        continue

    # Copy each figure with company name prefix
    for fig in figures_dir.iterdir():
        if fig.is_file():
            new_name = f"{company_dir.name}_{fig.name}"
            fig.rename(output_dir / new_name)

100%|██████████| 281/281 [00:01<00:00, 148.84it/s]

In [22]:
for pdf_dir in tqdm(
    list(Path("../data/processed/adobe_extracted").iterdir()), leave=False
):
    filter_photos(pdf_dir / "figures")

  0%|          | 0/281 [00:00<?, ?it/s]

Error processing fileoutpart11.png: Can only use .str accessor with string values!

100%|██████████| 12/12 [00:16<00:00,  1.37s/it]
100%|██████████| 4/4 [00:01<00:00,  2.45it/s]t]
100%|██████████| 8/8 [00:06<00:00,  1.16it/s]t]
100%|██████████| 8/8 [00:47<00:00,  5.98s/it]t]
100%|██████████| 17/17 [00:11<00:00,  1.43it/s]t]
100%|██████████| 12/12 [00:27<00:00,  2.29s/it]t]
  3%|▎         | 8/281 [01:52<1:25:28, 18.78s/it]

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 28/28 [01:04<00:00,  2.30s/it]
  3%|▎         | 9/281 [02:56<2:25:52, 32.18s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 12/12 [00:11<00:00,  1.00it/s]
  4%|▎         | 10/281 [03:08<1:58:24, 26.21s/it]

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart71.png: Can only use .str accessor with string values!

Error processing fileoutpart70.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart72.png: Can only use .str accessor with string values!

Error processing fileoutpart73.png: Can only use .str accessor with string values!

100%|██████████| 70/70 [01:31<00:00,  1.31s/it]
100%|██████████| 21/21 [01:05<00:00,  3.11s/it]it]
  4%|▍         | 12/281 [05:46<3:51:03, 51.54s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart51.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 53/53 [00:16<00:00,  3.23it/s]
  5%|▍         | 13/281 [06:02<3:03:24, 41.06s/it]

Error processing fileoutpart49.png: Can only use .str accessor with string values!

Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart60.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!
Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!

Error processing fileoutpart55.png: Can only use .str accessor with string values!
Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart66.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart54.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart59.png: Can only use .str accessor with string values!

Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 83/83 [00:33<00:00,  2.45it/s]
  5%|▍         | 14/281 [06:36<2:53:16, 38.94s/it]

Error processing fileoutpart80.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

100%|██████████| 18/18 [00:17<00:00,  1.06it/s]
  6%|▌         | 16/281 [06:53<1:50:07, 24.93s/it]

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart83.png: Can only use .str accessor with string values!
Error processing fileoutpart78.png: Can only use .str accessor with string values!

Error processing fileoutpart71.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart76.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!
Error processing fileoutpart77.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart60.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart70.png: Can only use .str accessor with string values!

Error processing fileoutpart84.png: Can only use .str accessor with string values!

Error processing fileoutpart74.png: Can only use .str accessor with string values!
Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart58.png: Can only use .str accessor with string values!
Error processing fileoutpart85.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!
Error processing fileoutpart81.png: Can only use .str accessor with string values!

Error processing fileoutpart66.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart75.png: Can only use .str accessor with string values!

Error processing fileoutpart54.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart72.png: Can only use .str accessor with string values!
Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart67.png: Can only use .str accessor with string values!
Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart73.png: Can only use .str accessor with string values!
Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart68.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart79.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart82.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

Error processing fileoutpart65.png: Can only use .str accessor with string values!
Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart59.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!
Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 88/88 [00:24<00:00,  3.53it/s]
  6%|▌         | 17/281 [07:18<1:49:42, 24.94s/it]

Error processing fileoutpart80.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 11/11 [00:10<00:00,  1.02it/s]
  6%|▋         | 18/281 [07:29<1:33:02, 21.23s/it]

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:13<00:00,  1.90it/s]
  7%|▋         | 19/281 [07:42<1:23:44, 19.18s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!
Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!

100%|██████████| 54/54 [00:51<00:00,  1.05it/s]
  7%|▋         | 21/281 [08:34<1:35:24, 22.02s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:01<00:00,  3.62it/s]
  8%|▊         | 22/281 [08:36<1:14:25, 17.24s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

100%|██████████| 31/31 [00:42<00:00,  1.38s/it]
100%|██████████| 1/1 [00:00<00:00,  5.85it/s]s/it]
  9%|▊         | 24/281 [09:19<1:14:53, 17.48s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart83.png: Can only use .str accessor with string values!

Error processing fileoutpart78.png: Can only use .str accessor with string values!
Error processing fileoutpart88.png: Can only use .str accessor with string values!

Error processing fileoutpart71.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart76.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!
Error processing fileoutpart77.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!
Error processing fileoutpart114.png: Can only use .str accessor with string values!

Error processing fileoutpart152.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart60.png: Can only use .str accessor with string values!
Error processing fileoutpart158.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart94.png: Can only use .str accessor with string values!

Error processing fileoutpart70.png: Can only use .str accessor with string values!
Error processing fileoutpart91.png: Can only use .str accessor with string values!

Error processing fileoutpart110.png: Can only use .str accessor with string values!
Error processing fileoutpart84.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!
Error processing fileoutpart74.png: Can only use .str accessor with string values!

Error processing fileoutpart103.png: Can only use .str accessor with string values!
Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!
Error processing fileoutpart135.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart124.png: Can only use .str accessor with string values!

Error processing fileoutpart163.png: Can only use .str accessor with string values!
Error processing fileoutpart92.png: Can only use .str accessor with string values!

Error processing fileoutpart139.png: Can only use .str accessor with string values!
Error processing fileoutpart127.png: Can only use .str accessor with string values!

Error processing fileoutpart58.png: Can only use .str accessor with string values!
Error processing fileoutpart85.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart111.png: Can only use .str accessor with string values!

Error processing fileoutpart81.png: Can only use .str accessor with string values!

Error processing fileoutpart87.png: Can only use .str accessor with string values!
Error processing fileoutpart155.png: Can only use .str accessor with string values!

Error processing fileoutpart121.png: Can only use .str accessor with string values!
Error processing fileoutpart66.png: Can only use .str accessor with string values!

Error processing fileoutpart120.png: Can only use .str accessor with string values!
Error processing fileoutpart133.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart104.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart75.png: Can only use .str accessor with string values!
Error processing fileoutpart134.png: Can only use .str accessor with string values!

Error processing fileoutpart156.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart116.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart162.png: Can only use .str accessor with string values!
Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart118.png: Can only use .str accessor with string values!
Error processing fileoutpart101.png: Can only use .str accessor with string values!

Error processing fileoutpart115.png: Can only use .str accessor with string values!
Error processing fileoutpart131.png: Can only use .str accessor with string values!

Error processing fileoutpart106.png: Can only use .str accessor with string values!
Error processing fileoutpart132.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart72.png: Can only use .str accessor with string values!

Error processing fileoutpart113.png: Can only use .str accessor with string values!
Error processing fileoutpart93.png: Can only use .str accessor with string values!

Error processing fileoutpart64.png: Can only use .str accessor with string values!
Error processing fileoutpart67.png: Can only use .str accessor with string values!

Error processing fileoutpart119.png: Can only use .str accessor with string values!
Error processing fileoutpart161.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart73.png: Can only use .str accessor with string values!

Error processing fileoutpart129.png: Can only use .str accessor with string values!
Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart157.png: Can only use .str accessor with string values!
Error processing fileoutpart108.png: Can only use .str accessor with string values!

Error processing fileoutpart136.png: Can only use .str accessor with string values!
Error processing fileoutpart68.png: Can only use .str accessor with string values!

Error processing fileoutpart100.png: Can only use .str accessor with string values!
Error processing fileoutpart89.png: Can only use .str accessor with string values!

Error processing fileoutpart130.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart96.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart98.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart97.png: Can only use .str accessor with string values!

Error processing fileoutpart128.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart154.png: Can only use .str accessor with string values!
Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart153.png: Can only use .str accessor with string values!

Error processing fileoutpart79.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart117.png: Can only use .str accessor with string values!
Error processing fileoutpart107.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart105.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart160.png: Can only use .str accessor with string values!

Error processing fileoutpart95.png: Can only use .str accessor with string values!
Error processing fileoutpart86.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart112.png: Can only use .str accessor with string values!

Error processing fileoutpart109.png: Can only use .str accessor with string values!
Error processing fileoutpart82.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart122.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart137.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart123.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

Error processing fileoutpart126.png: Can only use .str accessor with string values!
Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart165.png: Can only use .str accessor with string values!
Error processing fileoutpart65.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart164.png: Can only use .str accessor with string values!
Error processing fileoutpart125.png: Can only use .str accessor with string values!

Error processing fileoutpart59.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart99.png: Can only use .str accessor with string values!
Error processing fileoutpart159.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!
Error processing fileoutpart138.png: Can only use .str accessor with string values!

Error processing fileoutpart7.png: Can only use .str accessor with string values!
Error processing fileoutpart80.png: Can only use .str accessor with string values!

100%|██████████| 148/148 [00:22<00:00,  6.55it/s]
  9%|▉         | 26/281 [09:41<1:02:57, 14.81s/it]

Error processing fileoutpart102.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!
Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart77.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart67.png: Can only use .str accessor with string values!
Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 74/74 [00:49<00:00,  1.49it/s]
 10%|▉         | 27/281 [10:31<1:37:30, 23.03s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart60.png: Can only use .str accessor with string values!

Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 46/46 [01:14<00:00,  1.62s/it]
 10%|▉         | 28/281 [11:45<2:31:39, 35.97s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

100%|██████████| 18/18 [00:02<00:00,  7.01it/s]
 10%|█         | 29/281 [11:48<1:53:56, 27.13s/it]

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 2/2 [00:00<00:00,  5.55it/s]
 11%|█         | 30/281 [11:48<1:22:46, 19.79s/it]

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 23/23 [00:33<00:00,  1.46s/it]
 11%|█         | 31/281 [12:22<1:38:42, 23.69s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!

 33%|███▎      | 7/21 [00:01<00:03,  4.45it/s]

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

100%|██████████| 21/21 [00:13<00:00,  1.54it/s]
 11%|█▏        | 32/281 [12:36<1:26:18, 20.80s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 6/6 [00:00<00:00,  7.79it/s]
 12%|█▏        | 33/281 [12:36<1:01:54, 14.98s/it]

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 15/15 [00:46<00:00,  3.07s/it]
 12%|█▏        | 34/281 [13:22<1:39:09, 24.09s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 23/23 [00:15<00:00,  1.46it/s]
 13%|█▎        | 36/281 [13:38<1:08:09, 16.69s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

100%|██████████| 9/9 [00:11<00:00,  1.28s/it]
 13%|█▎        | 37/281 [13:50<1:02:43, 15.43s/it]

Error processing fileoutpart14.png: Can only use .str accessor with string values!

100%|██████████| 11/11 [00:19<00:00,  1.74s/it]
 14%|█▍        | 39/281 [14:09<52:29, 13.02s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

 44%|████▍     | 11/25 [00:03<00:03,  4.06it/s]

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 25/25 [00:10<00:00,  2.43it/s]
 14%|█▍        | 40/281 [14:19<49:48, 12.40s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

100%|██████████| 22/22 [00:11<00:00,  1.99it/s]
 15%|█▍        | 41/281 [14:30<48:15, 12.07s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!

100%|██████████| 20/20 [00:55<00:00,  2.75s/it]
 15%|█▍        | 42/281 [15:25<1:32:27, 23.21s/it]

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!
Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

100%|██████████| 32/32 [01:57<00:00,  3.66s/it]
 15%|█▌        | 43/281 [17:22<3:12:42, 48.58s/it]

Error processing fileoutpart31.png: Can only use .str accessor with string values!
Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart76.png: Can only use .str accessor with string values!

Error processing fileoutpart77.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

100%|██████████| 48/48 [00:28<00:00,  1.66it/s]
 16%|█▌        | 44/281 [17:51<2:50:16, 43.11s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart33.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:10<00:00,  2.44it/s]
 16%|█▌        | 45/281 [18:02<2:13:13, 33.87s/it]

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

100%|██████████| 16/16 [00:16<00:00,  1.01s/it]
 17%|█▋        | 47/281 [18:18<1:27:00, 22.31s/it]

Error processing fileoutpart56.png: Can only use .str accessor with string values!
Error processing fileoutpart78.png: Can only use .str accessor with string values!
Error processing fileoutpart71.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart76.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart60.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart70.png: Can only use .str accessor with string values!

Error processing fileoutpart74.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!

Error processing fileoutpart55.png: Can only use .str accessor with string values!
Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart66.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart75.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart54.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart72.png: Can only use .str accessor with string values!
Error processing fileoutpart64.png: Can only use .str accessor with string values!
Error processing fileoutpart67.png: Can only use .str accessor with string values!
Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart73.png: Can only use .str accessor with string values!

Error processing fileoutpart68.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!
Error processing fileoutpart65.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart57.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 83/83 [00:28<00:00,  2.94it/s]
 17%|█▋        | 48/281 [18:46<1:32:14, 23.75s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

100%|██████████| 31/31 [02:00<00:00,  3.89s/it]
 17%|█▋        | 49/281 [20:47<3:08:15, 48.69s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

100%|██████████| 42/42 [00:36<00:00,  1.14it/s]
 18%|█▊        | 50/281 [21:24<2:55:04, 45.48s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 15/15 [00:05<00:00,  2.75it/s]
 18%|█▊        | 51/281 [21:29<2:11:44, 34.37s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

100%|██████████| 27/27 [00:58<00:00,  2.16s/it]
 19%|█▊        | 52/281 [22:27<2:37:08, 41.17s/it]

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

100%|██████████| 24/24 [00:16<00:00,  1.42it/s]
 19%|█▉        | 53/281 [22:44<2:09:51, 34.17s/it]

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

100%|██████████| 21/21 [00:14<00:00,  1.48it/s]
 19%|█▉        | 54/281 [22:58<1:47:10, 28.33s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

100%|██████████| 25/25 [00:09<00:00,  2.76it/s]
 20%|█▉        | 55/281 [23:07<1:25:20, 22.66s/it]

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 9/9 [00:14<00:00,  1.59s/it]
 20%|█▉        | 56/281 [23:22<1:15:43, 20.19s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

100%|██████████| 19/19 [00:25<00:00,  1.33s/it]
 20%|██        | 57/281 [23:47<1:21:00, 21.70s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 25/25 [00:10<00:00,  2.33it/s]
 21%|██        | 58/281 [23:58<1:08:30, 18.43s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 28/28 [00:18<00:00,  1.54it/s]
 21%|██        | 59/281 [24:16<1:07:52, 18.35s/it]

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 27/27 [01:08<00:00,  2.54s/it]
100%|██████████| 9/9 [00:26<00:00,  2.99s/it]s/it]
 22%|██▏       | 62/281 [25:51<1:34:48, 25.98s/it]

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 16/16 [00:13<00:00,  1.18it/s]
 22%|██▏       | 63/281 [26:05<1:22:39, 22.75s/it]

Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

100%|██████████| 58/58 [01:42<00:00,  1.77s/it]
 23%|██▎       | 64/281 [27:48<2:40:45, 44.45s/it]

Error processing fileoutpart9.png: Can only use .str accessor with string values!

100%|██████████| 2/2 [00:01<00:00,  1.69it/s]
 23%|██▎       | 65/281 [27:49<1:56:28, 32.35s/it]

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 66/66 [00:59<00:00,  1.12it/s]
100%|██████████| 6/6 [00:11<00:00,  1.97s/it]s/it]
100%|██████████| 12/12 [01:05<00:00,  5.49s/it]it]
100%|██████████| 24/24 [00:46<00:00,  1.92s/it]it]
 25%|██▍       | 69/281 [30:52<2:32:11, 43.07s/it]

Error processing fileoutpart2.png: Can only use .str accessor with string values!

100%|██████████| 30/30 [00:23<00:00,  1.25it/s]
 25%|██▍       | 70/281 [31:16<2:11:32, 37.41s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:34<00:00,  4.97s/it]
 25%|██▌       | 71/281 [31:51<2:08:10, 36.62s/it]

Error processing fileoutpart83.png: Can only use .str accessor with string values!
Error processing fileoutpart78.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart70.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!
Error processing fileoutpart81.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart73.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart82.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!
Error processing fileoutpart65.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 87/87 [00:34<00:00,  2.49it/s]
100%|██████████| 15/15 [00:18<00:00,  1.26s/it]it]
 26%|██▋       | 74/281 [32:44<1:28:28, 25.64s/it]

Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart55.png: Can only use .str accessor with string values!
Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart54.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart67.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart59.png: Can only use .str accessor with string values!

100%|██████████| 68/68 [01:37<00:00,  1.43s/it]
 27%|██▋       | 75/281 [34:22<2:32:25, 44.39s/it]

Error processing fileoutpart57.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!
Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 35/35 [00:07<00:00,  4.52it/s]
 27%|██▋       | 76/281 [34:30<1:57:41, 34.44s/it]

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 17/17 [00:44<00:00,  2.61s/it]
100%|██████████| 16/16 [00:43<00:00,  2.74s/it]it]
 28%|██▊       | 78/281 [35:58<2:12:17, 39.10s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 25/25 [00:10<00:00,  2.36it/s]
 28%|██▊       | 79/281 [36:09<1:43:52, 30.86s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart56.png: Can only use .str accessor with string values!
Error processing fileoutpart71.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart60.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart70.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!
Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!
Error processing fileoutpart69.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart55.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart66.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart54.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart47.png: Can only use .str accessor with string values!
Error processing fileoutpart65.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart49.png: Can only use .str accessor with string values!

Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 72/72 [01:09<00:00,  1.04it/s]
100%|██████████| 19/19 [00:08<00:00,  2.35it/s]it]
 29%|██▉       | 81/281 [37:26<1:47:06, 32.13s/it]

Error processing fileoutpart2.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:03<00:00,  2.33it/s]
 29%|██▉       | 82/281 [37:29<1:17:57, 23.50s/it]

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

100%|██████████| 16/16 [00:18<00:00,  1.15s/it]
100%|██████████| 11/11 [00:08<00:00,  1.23it/s]it]
 30%|██▉       | 84/281 [37:57<59:25, 18.10s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!
Error processing fileoutpart38.png: Can only use .str accessor with string values!
Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!
Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart54.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart49.png: Can only use .str accessor with string values!

100%|██████████| 74/74 [00:31<00:00,  2.37it/s]
 30%|███       | 85/281 [38:28<1:11:57, 22.03s/it]

Error processing fileoutpart57.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 8/8 [00:16<00:00,  2.03s/it]
 31%|███       | 86/281 [38:44<1:05:59, 20.31s/it]

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:06<00:00,  1.09it/s]
100%|██████████| 6/6 [00:26<00:00,  4.48s/it]it]
 31%|███▏      | 88/281 [39:17<1:02:18, 19.37s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!

100%|██████████| 79/79 [01:12<00:00,  1.10it/s]
 32%|███▏      | 89/281 [40:30<1:52:35, 35.18s/it]

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!

100%|██████████| 20/20 [00:13<00:00,  1.49it/s]
 32%|███▏      | 90/281 [40:43<1:31:13, 28.66s/it]

Error processing fileoutpart10.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 5/5 [00:02<00:00,  2.17it/s]
 32%|███▏      | 91/281 [40:45<1:05:43, 20.76s/it]

Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!

100%|██████████| 40/40 [00:27<00:00,  1.46it/s]
100%|██████████| 12/12 [00:03<00:00,  3.08it/s]it]
 33%|███▎      | 93/281 [41:17<53:34, 17.10s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

100%|██████████| 30/30 [00:10<00:00,  2.81it/s]
 33%|███▎      | 94/281 [41:27<47:18, 15.18s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

100%|██████████| 12/12 [00:12<00:00,  1.07s/it]
 34%|███▍      | 96/281 [41:40<34:22, 11.15s/it]

Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart55.png: Can only use .str accessor with string values!

Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!
Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart54.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 46/46 [00:33<00:00,  1.38it/s]
 35%|███▍      | 97/281 [42:14<51:07, 16.67s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

100%|██████████| 31/31 [00:38<00:00,  1.25s/it]
 35%|███▍      | 98/281 [42:52<1:08:22, 22.42s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:01<00:00,  6.94it/s]
100%|██████████| 3/3 [00:01<00:00,  2.00it/s]it]
 36%|███▌      | 101/281 [42:55<29:00,  9.67s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart78.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!
Error processing fileoutpart77.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart70.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!
Error processing fileoutpart74.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

 25%|██▍       | 19/77 [00:04<00:12,  4.49it/s]

Error processing fileoutpart63.png: Can only use .str accessor with string values!
Error processing fileoutpart69.png: Can only use .str accessor with string values!

Error processing fileoutpart58.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart81.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart72.png: Can only use .str accessor with string values!
Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart73.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!
Error processing fileoutpart68.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart57.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 77/77 [00:21<00:00,  3.62it/s]
 36%|███▋      | 102/281 [43:16<37:04, 12.43s/it]

Error processing fileoutpart80.png: Can only use .str accessor with string values!

100%|██████████| 1/1 [00:00<00:00,  3.61it/s]
100%|██████████| 1/1 [00:00<00:00,  4.89it/s]/it]
 37%|███▋      | 104/281 [43:17<20:24,  6.92s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

100%|██████████| 22/22 [00:40<00:00,  1.85s/it]
 38%|███▊      | 106/281 [43:57<37:02, 12.70s/it]

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 13/13 [00:01<00:00,  7.34it/s]
 38%|███▊      | 107/281 [43:59<29:21, 10.13s/it]

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!

100%|██████████| 30/30 [00:23<00:00,  1.26it/s]
 38%|███▊      | 108/281 [44:23<39:09, 13.58s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 5/5 [00:04<00:00,  1.09it/s]
 39%|███▉      | 109/281 [44:27<32:06, 11.20s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:10<00:00,  2.44it/s]
 39%|███▉      | 110/281 [44:38<31:30, 11.05s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 2/2 [00:03<00:00,  1.98s/it]
 40%|███▉      | 111/281 [44:42<25:39,  9.06s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!
Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

100%|██████████| 45/45 [00:22<00:00,  2.01it/s]
 40%|███▉      | 112/281 [45:04<36:18, 12.89s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart32.png: Can only use .str accessor with string values!

100%|██████████| 37/37 [00:12<00:00,  2.85it/s]
 40%|████      | 113/281 [45:17<36:10, 12.92s/it]

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 40/40 [00:24<00:00,  1.61it/s]
 41%|████      | 114/281 [45:42<45:44, 16.43s/it]

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 16/16 [00:40<00:00,  2.50s/it]
 41%|████      | 115/281 [46:22<1:04:43, 23.40s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

100%|██████████| 3/3 [00:05<00:00,  1.67s/it]
 41%|████▏     | 116/281 [46:27<49:20, 17.94s/it]

Error processing fileoutpart25.png: Can only use .str accessor with string values!

100%|██████████| 63/63 [01:16<00:00,  1.22s/it]
100%|██████████| 14/14 [00:19<00:00,  1.36s/it]/it]
 42%|████▏     | 118/281 [48:03<1:23:09, 30.61s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 9/9 [00:01<00:00,  4.73it/s]
 42%|████▏     | 119/281 [48:05<59:29, 22.03s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

100%|██████████| 14/14 [00:06<00:00,  2.17it/s]
100%|██████████| 10/10 [00:07<00:00,  1.42it/s]t]
 43%|████▎     | 121/281 [48:19<38:05, 14.29s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

100%|██████████| 29/29 [00:21<00:00,  1.37it/s]
100%|██████████| 25/25 [01:34<00:00,  3.80s/it]t]
100%|██████████| 15/15 [01:04<00:00,  4.32s/it]/it]
100%|██████████| 5/5 [00:04<00:00,  1.14it/s]6s/it]
 44%|████▍     | 125/281 [51:24<1:29:39, 34.48s/it]

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:09<00:00,  1.34s/it]
 45%|████▍     | 126/281 [51:34<1:09:38, 26.96s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!
Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!
Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart55.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart54.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart39.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!
Error processing fileoutpart57.png: Can only use .str accessor with string values!

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 80/80 [01:14<00:00,  1.08it/s]
100%|██████████| 1/1 [00:02<00:00,  2.92s/it]7s/it]
 46%|████▌     | 128/281 [52:51<1:15:43, 29.70s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 16/16 [00:05<00:00,  2.90it/s]
 46%|████▌     | 129/281 [52:56<56:51, 22.45s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 16/16 [00:45<00:00,  2.85s/it]
 46%|████▋     | 130/281 [53:42<1:13:55, 29.38s/it]

Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart77.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart55.png: Can only use .str accessor with string values!
Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart66.png: Can only use .str accessor with string values!

Error processing fileoutpart54.png: Can only use .str accessor with string values!

Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart65.png: Can only use .str accessor with string values!

100%|██████████| 74/74 [01:02<00:00,  1.18it/s]
 47%|████▋     | 131/281 [54:45<1:38:36, 39.45s/it]

Error processing fileoutpart49.png: Can only use .str accessor with string values!
Error processing fileoutpart57.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!

 88%|████████▊ | 35/40 [00:38<00:04,  1.16it/s]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 40/40 [00:50<00:00,  1.27s/it]
 47%|████▋     | 132/281 [55:36<1:46:21, 42.83s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

100%|██████████| 38/38 [00:34<00:00,  1.09it/s]
 47%|████▋     | 133/281 [56:10<1:39:47, 40.46s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 27/27 [00:03<00:00,  8.52it/s]
 48%|████▊     | 134/281 [56:14<1:11:43, 29.27s/it]

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart90.png: Can only use .str accessor with string values!

Error processing fileoutpart89.png: Can only use .str accessor with string values!

100%|██████████| 51/51 [01:59<00:00,  2.34s/it]
 48%|████▊     | 135/281 [58:13<2:17:02, 56.32s/it]

Error processing fileoutpart49.png: Can only use .str accessor with string values!

Error processing fileoutpart792.png: Can only use .str accessor with string values!

Error processing fileoutpart781.png: Can only use .str accessor with string values!

Error processing fileoutpart795.png: Can only use .str accessor with string values!

Error processing fileoutpart386.png: Can only use .str accessor with string values!

Error processing fileoutpart415.png: Can only use .str accessor with string values!

Error processing fileoutpart793.png: Can only use .str accessor with string values!

Error processing fileoutpart767.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart768.png: Can only use .str accessor with string values!

Error processing fileoutpart731.png: Can only use .str accessor with string values!

Error processing fileoutpart810.png: Can only use .str accessor with string values!

100%|██████████| 787/787 [03:27<00:00,  3.80it/s]
100%|██████████| 8/8 [00:28<00:00,  3.51s/it]1.54s/it]
 49%|████▉     | 137/281 [1:02:08<3:10:49, 79.51s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!
Error processing fileoutpart48.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart43.png: Can only use .str accessor with string values!
Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

 67%|██████▋   | 36/54 [00:09<00:03,  5.95it/s]

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!
Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart49.png: Can only use .str accessor with string values!

100%|██████████| 54/54 [00:19<00:00,  2.72it/s]
 49%|████▉     | 138/281 [1:02:28<2:26:51, 61.62s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 12/12 [00:32<00:00,  2.71s/it]
100%|██████████| 7/7 [00:15<00:00,  2.27s/it].90s/it]
 50%|█████     | 141/281 [1:03:17<1:15:02, 32.16s/it]

Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 23/23 [00:55<00:00,  2.42s/it]
 51%|█████     | 142/281 [1:04:12<1:27:58, 37.97s/it]

Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 12/12 [00:12<00:00,  1.06s/it]
 51%|█████     | 143/281 [1:04:25<1:12:07, 31.36s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 36/36 [00:41<00:00,  1.14s/it]
 51%|█████     | 144/281 [1:05:06<1:17:37, 34.00s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 15/15 [00:22<00:00,  1.50s/it]
100%|██████████| 9/9 [00:03<00:00,  2.70it/s].77s/it]
 52%|█████▏    | 146/281 [1:05:32<51:37, 22.94s/it]

Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 30/30 [00:53<00:00,  1.77s/it]
 52%|█████▏    | 147/281 [1:06:25<1:10:46, 31.69s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

100%|██████████| 37/37 [00:14<00:00,  2.63it/s]
 53%|█████▎    | 148/281 [1:06:39<58:48, 26.53s/it]

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

100%|██████████| 10/10 [00:09<00:00,  1.08it/s]
 53%|█████▎    | 149/281 [1:06:48<47:09, 21.43s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

100%|██████████| 15/15 [00:23<00:00,  1.59s/it]
100%|██████████| 2/2 [00:00<00:00,  9.62it/s]5s/it]
 54%|█████▎    | 151/281 [1:07:12<33:51, 15.62s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 11/11 [00:21<00:00,  1.94s/it]
 54%|█████▍    | 152/281 [1:07:34<37:14, 17.33s/it]

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

100%|██████████| 21/21 [00:13<00:00,  1.52it/s]
100%|██████████| 8/8 [00:37<00:00,  4.70s/it]9s/it]
 55%|█████▍    | 154/281 [1:08:25<47:59, 22.67s/it]

Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

100%|██████████| 6/6 [00:00<00:00,  6.05it/s]
 55%|█████▌    | 155/281 [1:08:26<33:59, 16.18s/it]

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 11/11 [00:05<00:00,  2.03it/s]
 56%|█████▌    | 156/281 [1:08:32<27:00, 12.96s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 6/6 [00:26<00:00,  4.39s/it]
100%|██████████| 5/5 [00:01<00:00,  3.50it/s]7s/it]
 56%|█████▌    | 158/281 [1:08:59<25:14, 12.31s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:10<00:00,  2.38it/s]
 57%|█████▋    | 159/281 [1:09:10<24:11, 11.90s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 2/2 [00:02<00:00,  1.07s/it]
 57%|█████▋    | 160/281 [1:09:12<18:05,  8.97s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:11<00:00,  2.21it/s]
 57%|█████▋    | 161/281 [1:09:24<19:38,  9.82s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!
Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!
Error processing fileoutpart32.png: Can only use .str accessor with string values!

100%|██████████| 45/45 [00:15<00:00,  2.82it/s]
 58%|█████▊    | 162/281 [1:09:40<23:08, 11.66s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

100%|██████████| 35/35 [00:45<00:00,  1.29s/it]
 58%|█████▊    | 163/281 [1:10:25<42:39, 21.69s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 17/17 [00:11<00:00,  1.48it/s]
 58%|█████▊    | 164/281 [1:10:37<36:19, 18.63s/it]

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 11/11 [00:43<00:00,  3.94s/it]
 59%|█████▊    | 165/281 [1:11:20<50:19, 26.03s/it]

Error processing fileoutpart83.png: Can only use .str accessor with string values!

Error processing fileoutpart78.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart106.png: Can only use .str accessor with string values!
Error processing fileoutpart90.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart108.png: Can only use .str accessor with string values!

Error processing fileoutpart100.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart107.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart105.png: Can only use .str accessor with string values!

Error processing fileoutpart109.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!

100%|██████████| 127/127 [03:06<00:00,  1.47s/it]
100%|██████████| 12/12 [00:16<00:00,  1.35s/it]5s/it]
 59%|█████▉    | 167/281 [1:14:43<1:47:52, 56.77s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 10/10 [00:21<00:00,  2.17s/it]
100%|██████████| 6/6 [00:06<00:00,  1.07s/it].26s/it]
 60%|██████    | 169/281 [1:15:11<1:04:03, 34.31s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!
Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!

100%|██████████| 44/44 [00:08<00:00,  4.89it/s]
 60%|██████    | 170/281 [1:15:20<49:26, 26.72s/it]

Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 18/18 [00:50<00:00,  2.80s/it]
 61%|██████    | 172/281 [1:16:10<47:15, 26.02s/it]

Error processing fileoutpart83.png: Can only use .str accessor with string values!
Error processing fileoutpart78.png: Can only use .str accessor with string values!
Error processing fileoutpart88.png: Can only use .str accessor with string values!

Error processing fileoutpart71.png: Can only use .str accessor with string values!

Error processing fileoutpart76.png: Can only use .str accessor with string values!
Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart77.png: Can only use .str accessor with string values!
Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart114.png: Can only use .str accessor with string values!
Error processing fileoutpart152.png: Can only use .str accessor with string values!

Error processing fileoutpart140.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!
Error processing fileoutpart60.png: Can only use .str accessor with string values!

 12%|█▏        | 14/118 [00:01<00:11,  9.09it/s]

Error processing fileoutpart94.png: Can only use .str accessor with string values!
Error processing fileoutpart70.png: Can only use .str accessor with string values!
Error processing fileoutpart91.png: Can only use .str accessor with string values!

Error processing fileoutpart110.png: Can only use .str accessor with string values!
Error processing fileoutpart84.png: Can only use .str accessor with string values!
Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart74.png: Can only use .str accessor with string values!
Error processing fileoutpart103.png: Can only use .str accessor with string values!
Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!
Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!
Error processing fileoutpart135.png: Can only use .str accessor with string values!

Error processing fileoutpart143.png: Can only use .str accessor with string values!
Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart92.png: Can only use .str accessor with string values!
Error processing fileoutpart144.png: Can only use .str accessor with string values!

Error processing fileoutpart139.png: Can only use .str accessor with string values!
Error processing fileoutpart127.png: Can only use .str accessor with string values!
Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart85.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!
Error processing fileoutpart111.png: Can only use .str accessor with string values!

Error processing fileoutpart87.png: Can only use .str accessor with string values!
Error processing fileoutpart121.png: Can only use .str accessor with string values!
Error processing fileoutpart120.png: Can only use .str accessor with string values!

Error processing fileoutpart133.png: Can only use .str accessor with string values!
Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart104.png: Can only use .str accessor with string values!
Error processing fileoutpart75.png: Can only use .str accessor with string values!

Error processing fileoutpart134.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart54.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart101.png: Can only use .str accessor with string values!
Error processing fileoutpart115.png: Can only use .str accessor with string values!
Error processing fileoutpart131.png: Can only use .str accessor with string values!

Error processing fileoutpart106.png: Can only use .str accessor with string values!
Error processing fileoutpart132.png: Can only use .str accessor with string values!
Error processing fileoutpart90.png: Can only use .str accessor with string values!

Error processing fileoutpart72.png: Can only use .str accessor with string values!
Error processing fileoutpart113.png: Can only use .str accessor with string values!

Error processing fileoutpart93.png: Can only use .str accessor with string values!
Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart142.png: Can only use .str accessor with string values!
Error processing fileoutpart145.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart73.png: Can only use .str accessor with string values!

Error processing fileoutpart129.png: Can only use .str accessor with string values!
Error processing fileoutpart33.png: Can only use .str accessor with string values!
Error processing fileoutpart108.png: Can only use .str accessor with string values!

Error processing fileoutpart136.png: Can only use .str accessor with string values!
Error processing fileoutpart68.png: Can only use .str accessor with string values!

Error processing fileoutpart100.png: Can only use .str accessor with string values!
Error processing fileoutpart89.png: Can only use .str accessor with string values!

Error processing fileoutpart147.png: Can only use .str accessor with string values!
Error processing fileoutpart130.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart98.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart128.png: Can only use .str accessor with string values!
Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart153.png: Can only use .str accessor with string values!
Error processing fileoutpart79.png: Can only use .str accessor with string values!

Error processing fileoutpart107.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart148.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!
Error processing fileoutpart105.png: Can only use .str accessor with string values!

Error processing fileoutpart146.png: Can only use .str accessor with string values!
Error processing fileoutpart95.png: Can only use .str accessor with string values!

Error processing fileoutpart86.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart112.png: Can only use .str accessor with string values!

 79%|███████▉  | 93/118 [00:11<00:03,  8.29it/s]

Error processing fileoutpart109.png: Can only use .str accessor with string values!
Error processing fileoutpart141.png: Can only use .str accessor with string values!
Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart122.png: Can only use .str accessor with string values!
Error processing fileoutpart39.png: Can only use .str accessor with string values!

Error processing fileoutpart137.png: Can only use .str accessor with string values!
Error processing fileoutpart37.png: Can only use .str accessor with string values!
Error processing fileoutpart123.png: Can only use .str accessor with string values!

Error processing fileoutpart126.png: Can only use .str accessor with string values!
Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart65.png: Can only use .str accessor with string values!
Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart59.png: Can only use .str accessor with string values!
Error processing fileoutpart99.png: Can only use .str accessor with string values!

Error processing fileoutpart149.png: Can only use .str accessor with string values!
Error processing fileoutpart49.png: Can only use .str accessor with string values!

Error processing fileoutpart138.png: Can only use .str accessor with string values!
Error processing fileoutpart57.png: Can only use .str accessor with string values!

Error processing fileoutpart7.png: Can only use .str accessor with string values!
Error processing fileoutpart80.png: Can only use .str accessor with string values!

100%|██████████| 118/118 [00:14<00:00,  8.18it/s]
 62%|██████▏   | 173/281 [1:16:25<41:39, 23.14s/it]

Error processing fileoutpart102.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!

100%|██████████| 55/55 [00:59<00:00,  1.07s/it]
 62%|██████▏   | 174/281 [1:17:24<58:01, 32.54s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart71.png: Can only use .str accessor with string values!
Error processing fileoutpart31.png: Can only use .str accessor with string values!
Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart77.png: Can only use .str accessor with string values!
Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart60.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!
Error processing fileoutpart94.png: Can only use .str accessor with string values!

 15%|█▌        | 17/111 [00:03<00:14,  6.31it/s]

Error processing fileoutpart70.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!
Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!
Error processing fileoutpart69.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart55.png: Can only use .str accessor with string values!

Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart66.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart54.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart64.png: Can only use .str accessor with string values!
Error processing fileoutpart67.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart73.png: Can only use .str accessor with string values!
Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart68.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart79.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!
Error processing fileoutpart65.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!
Error processing fileoutpart59.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!
Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 111/111 [01:32<00:00,  1.20it/s]
 62%|██████▏   | 175/281 [1:18:56<1:26:21, 48.88s/it]

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:28<00:00,  1.09s/it]
 63%|██████▎   | 176/281 [1:19:25<1:15:26, 43.11s/it]

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 44/44 [00:46<00:00,  1.06s/it]
 63%|██████▎   | 177/281 [1:20:11<1:16:25, 44.09s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart71.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!
Error processing fileoutpart55.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart72.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!
Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart53.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 64/64 [00:10<00:00,  6.15it/s]
 63%|██████▎   | 178/281 [1:20:22<58:56, 34.34s/it]

Error processing fileoutpart49.png: Can only use .str accessor with string values!
Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
 64%|██████▎   | 179/281 [1:20:22<41:20, 24.32s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

100%|██████████| 1/1 [00:00<00:00,  2.42it/s]
 64%|██████▍   | 180/281 [1:20:22<29:04, 17.27s/it]

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:01<00:00,  5.79it/s]
 64%|██████▍   | 181/281 [1:20:23<20:51, 12.51s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart46.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:15<00:00,  1.71it/s]
 65%|██████▍   | 182/281 [1:20:39<21:57, 13.31s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 12/12 [00:19<00:00,  1.65s/it]
 65%|██████▌   | 183/281 [1:20:58<24:53, 15.24s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!
Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 14/14 [00:02<00:00,  5.57it/s]
 66%|██████▌   | 185/281 [1:21:01<14:05,  8.81s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

100%|██████████| 6/6 [00:05<00:00,  1.17it/s]
 66%|██████▌   | 186/281 [1:21:06<12:31,  7.91s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

100%|██████████| 2/2 [00:02<00:00,  1.05s/it]
 67%|██████▋   | 187/281 [1:21:08<10:00,  6.39s/it]

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!

100%|██████████| 31/31 [00:29<00:00,  1.05it/s]
100%|██████████| 1/1 [00:00<00:00,  5.73it/s]6s/it]
 68%|██████▊   | 190/281 [1:21:38<11:38,  7.67s/it]

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart36.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

100%|██████████| 37/37 [00:23<00:00,  1.56it/s]
100%|██████████| 2/2 [00:01<00:00,  1.67it/s]0s/it]
 68%|██████▊   | 192/281 [1:22:03<13:15,  8.94s/it]

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart39.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 42/42 [00:33<00:00,  1.25it/s]
 69%|██████▊   | 193/281 [1:22:36<22:59, 15.68s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!
Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 25/25 [00:08<00:00,  2.80it/s]
 69%|██████▉   | 194/281 [1:22:45<19:58, 13.78s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

100%|██████████| 17/17 [00:15<00:00,  1.09it/s]
100%|██████████| 8/8 [00:03<00:00,  2.16it/s]0s/it]
 70%|██████▉   | 196/281 [1:23:05<15:53, 11.22s/it]

Error processing fileoutpart71.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart59.png: Can only use .str accessor with string values!

100%|██████████| 67/67 [02:57<00:00,  2.64s/it]
100%|██████████| 6/6 [00:06<00:00,  1.13s/it].86s/it]
 70%|███████   | 198/281 [1:26:08<1:01:07, 44.18s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

100%|██████████| 21/21 [00:26<00:00,  1.24s/it]
 71%|███████   | 199/281 [1:26:34<53:02, 38.81s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!
Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart45.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 25/25 [00:11<00:00,  2.24it/s]
 71%|███████   | 200/281 [1:26:46<41:17, 30.58s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 18/18 [00:02<00:00,  7.18it/s]
 72%|███████▏  | 201/281 [1:26:48<29:36, 22.21s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 15/15 [00:21<00:00,  1.40s/it]
 72%|███████▏  | 202/281 [1:27:09<28:46, 21.86s/it]

Error processing fileoutpart6.png: Can only use .str accessor with string values!
Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:01<00:00,  4.06it/s]
 72%|███████▏  | 203/281 [1:27:11<20:35, 15.84s/it]

Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart60.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart62.png: Can only use .str accessor with string values!
Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart55.png: Can only use .str accessor with string values!
Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!
Error processing fileoutpart66.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart64.png: Can only use .str accessor with string values!

Error processing fileoutpart67.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart68.png: Can only use .str accessor with string values!

Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart65.png: Can only use .str accessor with string values!

Error processing fileoutpart59.png: Can only use .str accessor with string values!
Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 70/70 [00:44<00:00,  1.58it/s]
 73%|███████▎  | 204/281 [1:27:55<31:14, 24.35s/it]

Error processing fileoutpart5.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

100%|██████████| 7/7 [00:05<00:00,  1.34it/s]
 73%|███████▎  | 205/281 [1:28:00<23:35, 18.62s/it]

Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

100%|██████████| 12/12 [00:03<00:00,  3.25it/s]
100%|██████████| 11/11 [00:21<00:00,  1.95s/it]/it]
 74%|███████▎  | 207/281 [1:28:26<20:09, 16.35s/it]

Error processing fileoutpart31.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart35.png: Can only use .str accessor with string values!
Error processing fileoutpart18.png: Can only use .str accessor with string values!

Error processing fileoutpart63.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart122.png: Can only use .str accessor with string values!

Error processing fileoutpart65.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!

100%|██████████| 89/89 [02:05<00:00,  1.41s/it]
 74%|███████▍  | 208/281 [1:30:31<59:45, 49.12s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!

Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 22/22 [00:32<00:00,  1.49s/it]
100%|██████████| 5/5 [00:09<00:00,  1.99s/it]3s/it]
 75%|███████▍  | 210/281 [1:31:14<40:10, 33.95s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart13.png: Can only use .str accessor with string values!
Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

 29%|██▊       | 10/35 [00:07<00:19,  1.27it/s]

Error processing fileoutpart19.png: Can only use .str accessor with string values!
Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

100%|██████████| 35/35 [00:14<00:00,  2.46it/s]
100%|██████████| 5/5 [00:01<00:00,  2.51it/s]5s/it]
 75%|███████▌  | 212/281 [1:31:30<23:16, 20.23s/it]

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 23/23 [00:36<00:00,  1.57s/it]
 76%|███████▌  | 214/281 [1:32:07<21:30, 19.26s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart31.png: Can only use .str accessor with string values!
Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart38.png: Can only use .str accessor with string values!

Error processing fileoutpart4.png: Can only use .str accessor with string values!
Error processing fileoutpart35.png: Can only use .str accessor with string values!

Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart34.png: Can only use .str accessor with string values!

Error processing fileoutpart69.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!
Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart81.png: Can only use .str accessor with string values!

Error processing fileoutpart5.png: Can only use .str accessor with string values!
Error processing fileoutpart40.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!

Error processing fileoutpart29.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart33.png: Can only use .str accessor with string values!

Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!

Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!
Error processing fileoutpart30.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart39.png: Can only use .str accessor with string values!

Error processing fileoutpart37.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

Error processing fileoutpart47.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!

Error processing fileoutpart6.png: Can only use .str accessor with string values!

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 110/110 [00:56<00:00,  1.96it/s]
100%|██████████| 12/12 [01:24<00:00,  7.01s/it]/it]
 77%|███████▋  | 216/281 [1:34:27<46:34, 42.99s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!

Error processing fileoutpart18.png: Can only use .str accessor with string values!
Error processing fileoutpart27.png: Can only use .str accessor with string values!

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!
Error processing fileoutpart25.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

100%|██████████| 50/50 [00:30<00:00,  1.63it/s]
 77%|███████▋  | 217/281 [1:34:58<42:18, 39.67s/it]

Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 42/42 [01:16<00:00,  1.82s/it]
100%|██████████| 13/13 [00:22<00:00,  1.75s/it]/it]
 78%|███████▊  | 219/281 [1:36:37<43:34, 42.17s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!

 56%|█████▌    | 14/25 [00:07<00:06,  1.83it/s]

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!

Error processing fileoutpart8.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 25/25 [00:09<00:00,  2.66it/s]
 79%|███████▊  | 221/281 [1:36:46<25:20, 25.34s/it]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

100%|██████████| 1/1 [00:00<00:00,  4.19it/s]
 79%|███████▉  | 222/281 [1:36:46<18:55, 19.24s/it]

Error processing fileoutpart19.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 37/37 [00:37<00:00,  1.00s/it]
100%|██████████| 1/1 [00:01<00:00,  1.92s/it]6s/it]
100%|██████████| 5/5 [00:02<00:00,  2.19it/s]6s/it]
 80%|████████  | 225/281 [1:37:28<12:42, 13.61s/it]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 14/14 [00:20<00:00,  1.45s/it]
 81%|████████  | 227/281 [1:37:48<10:52, 12.08s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!

Error processing fileoutpart0.png: Can only use .str accessor with string values!
Error processing fileoutpart16.png: Can only use .str accessor with string values!

Error processing fileoutpart3.png: Can only use .str accessor with string values!
Error processing fileoutpart2.png: Can only use .str accessor with string values!

Error processing fileoutpart1.png: Can only use .str accessor with string values!

100%|██████████| 15/15 [00:06<00:00,  2.21it/s]
 81%|████████  | 228/281 [1:37:55<09:33, 10.81s/it]

Error processing fileoutpart24.png: Can only use .str accessor with string values!
Error processing fileoutpart56.png: Can only use .str accessor with string values!

Error processing fileoutpart48.png: Can only use .str accessor with string values!

Error processing fileoutpart60.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart61.png: Can only use .str accessor with string values!

Error processing fileoutpart58.png: Can only use .str accessor with string values!

Error processing fileoutpart28.png: Can only use .str accessor with string values!

Error processing fileoutpart52.png: Can only use .str accessor with string values!

Error processing fileoutpart40.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart44.png: Can only use .str accessor with string values!

Error processing fileoutpart90.png: Can only use .str accessor with string values!

Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!
Error processing fileoutpart50.png: Can only use .str accessor with string values!

Error processing fileoutpart26.png: Can only use .str accessor with string values!

Error processing fileoutpart51.png: Can only use .str accessor with string values!

Error processing fileoutpart30.png: Can only use .str accessor with string values!

Error processing fileoutpart45.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!

Error processing fileoutpart32.png: Can only use .str accessor with string values!
Error processing fileoutpart59.png: Can only use .str accessor with string values!

Error processing fileoutpart49.png: Can only use .str accessor with string values!
Error processing fileoutpart57.png: Can only use .str accessor with string values!

100%|██████████| 92/92 [00:38<00:00,  2.41it/s]
100%|██████████| 30/30 [01:04<00:00,  2.14s/it]/it]
100%|██████████| 4/4 [00:08<00:00,  2.24s/it]0s/it]
 82%|████████▏ | 231/281 [1:39:46<20:16, 24.33s/it]

Error processing fileoutpart13.png: Can only use .str accessor with string values!

Error processing fileoutpart43.png: Can only use .str accessor with string values!

Error processing fileoutpart14.png: Can only use .str accessor with string values!
Error processing fileoutpart22.png: Can only use .str accessor with string values!

Error processing fileoutpart21.png: Can only use .str accessor with string values!
Error processing fileoutpart9.png: Can only use .str accessor with string values!

 54%|█████▍    | 14/26 [00:09<00:08,  1.41it/s]

Error processing fileoutpart16.png: Can only use .str accessor with string values!
Error processing fileoutpart20.png: Can only use .str accessor with string values!
Error processing fileoutpart42.png: Can only use .str accessor with string values!

Error processing fileoutpart23.png: Can only use .str accessor with string values!
Error processing fileoutpart17.png: Can only use .str accessor with string values!
Error processing fileoutpart11.png: Can only use .str accessor with string values!

Error processing fileoutpart15.png: Can only use .str accessor with string values!

Error processing fileoutpart41.png: Can only use .str accessor with string values!
Error processing fileoutpart12.png: Can only use .str accessor with string values!
Error processing fileoutpart8.png: Can only use .str accessor with string values!

Error processing fileoutpart10.png: Can only use .str accessor with string values!

100%|██████████| 26/26 [00:12<00:00,  2.06it/s]

Error processing fileoutpart7.png: Can only use .str accessor with string values!

NotADirectoryError: [Errno 20] Not a directory: '../data/processed/adobe_extracted/.DS_Store/figures_accepted'

In [8]:
image_path = "../data/processed/adobe_extracted/ Monserate Winery (11)-merged/figures/fileoutpart2.png"

In [9]:
import pandas as pd

df = pd.DataFrame(columns=["img", "text_density", "color_std", "edge_density"])

for img in tqdm(
    list(
        Path(
            "../data/processed/adobe_extracted/ Monserate Winery (11)-merged/figures"
        ).iterdir()
    )
):
    properties = photo_properties(img)
    df = pd.concat(
        [
            df,
            pd.DataFrame(
                {
                    "img": img.name,
                    **properties,
                },
                index=[len(df)],
            ),
        ],
    )
df

  0%|          | 0/77 [00:00<?, ?it/s]/tmp/ipykernel_18344/4042842102.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
 14%|█▍        | 11/77 [00:06<00:20,  3.22it/s]

Error processing fileoutpart4.png: Can only use .str accessor with string values!

 57%|█████▋    | 44/77 [00:27<00:12,  2.69it/s]

Error processing fileoutpart29.png: Can only use .str accessor with string values!

 69%|██████▉   | 53/77 [00:35<00:17,  1.37it/s]

Error processing fileoutpart25.png: Can only use .str accessor with string values!

100%|██████████| 77/77 [00:48<00:00,  1.59it/s]

,img,text_density,color_std,edge_density,width,height,total_pixels
0,fileoutpart24.png,0.000000,64.603376,0.215412,1219.0,1310.0,1596890.0
1,fileoutpart56.png,0.000000,64.181394,0.041583,841.0,1056.0,888096.0
2,fileoutpart78.png,0.000000,58.700875,0.035482,1722.0,2299.0,3958878.0
3,fileoutpart71.png,0.000000,59.360535,0.052521,941.0,1725.0,1623225.0
4,fileoutpart31.png,0.000000,65.388021,0.098004,881.0,1281.0,1128561.0
...,...,...,...,...,...,...,...
72,fileoutpart59.png,0.000000,66.462315,0.032408,1032.0,1538.0,1587216.0
73,fileoutpart6.png,0.000000,57.943581,0.057450,1306.0,978.0,1277268.0
74,fileoutpart49.png,0.504513,45.824228,0.074481,400.0,77.0,30800.0
75,fileoutpart57.png,0.513300,46.333079,0.073534,401.0,78.0,31278.0
76,fileoutpart7.png,0.000000,46.743313,0.149150,642.0,1206.0,774252.0

In [12]:
import itables

itables.show(df)

In [11]:
bad_images = list(
    x.name
    for x in Path(
        "../data/processed/adobe_extracted/ Monserate Winery (11)-merged/figures copy"
    ).iterdir()
)
df["label"] = df["img"].apply(lambda x: "not photo" if x in bad_images else "photo")
df

,img,text_density,color_std,edge_density,width,height,total_pixels,label
0,fileoutpart24.png,0.000000,64.603376,0.215412,1219.0,1310.0,1596890.0,photo
1,fileoutpart56.png,0.000000,64.181394,0.041583,841.0,1056.0,888096.0,photo
2,fileoutpart78.png,0.000000,58.700875,0.035482,1722.0,2299.0,3958878.0,photo
3,fileoutpart71.png,0.000000,59.360535,0.052521,941.0,1725.0,1623225.0,photo
4,fileoutpart31.png,0.000000,65.388021,0.098004,881.0,1281.0,1128561.0,photo
...,...,...,...,...,...,...,...,...
72,fileoutpart59.png,0.000000,66.462315,0.032408,1032.0,1538.0,1587216.0,photo
73,fileoutpart6.png,0.000000,57.943581,0.057450,1306.0,978.0,1277268.0,photo
74,fileoutpart49.png,0.504513,45.824228,0.074481,400.0,77.0,30800.0,not photo
75,fileoutpart57.png,0.513300,46.333079,0.073534,401.0,78.0,31278.0,not photo
76,fileoutpart7.png,0.000000,46.743313,0.149150,642.0,1206.0,774252.0,photo

In [13]:
(text_density, color_std, edge_density)

(0.00040239210657175013, np.float64(25.11696419010659), 0.0467761740253169)

In [6]:
import os

os.listdir("../data/processed/adobe_extracted/ Monserate Winery (11)-merged")

['tables', 'figures', 'structuredData.json']